export { default as User } from "./User";
export { default as Donor } from "./Donor";
export { default as Donation } from "./Donation";
export { default as Content } from "./Content";
export { default as GalleryEvent } from "./GalleryEvent";
export { default as Setting } from "./Setting";
export { default as Certificate } from "./Certificate";
export { default as ContactInquiry } from "./ContactInquiry";
export { default as OTP } from "./OTP";
export { default as TrustDocument } from "./TrustDocument";

export type { IUser } from "./User";
export type { IDonor } from "./Donor";
export type { IDonation } from "./Donation";
export type { IContent } from "./Content";
export type { IGalleryEvent } from "./GalleryEvent";
export type { ISetting } from "./Setting";
export type { ICertificate } from "./Certificate";
export type { IContactInquiry } from "./ContactInquiry";
export type { IOTP } from "./OTP";
export type { ITrustDocument } from "./TrustDocument";
